const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const releaseFlags = require('../releaseFlags')[process.env.RELEASE_STAGE]
const template = 'src/index.ejs'

const plugins = [
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoEmitOnErrorsPlugin(),
  new webpack.DefinePlugin(
    Object.assign({}, releaseFlags)
  ),
  new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    template: template
  })
]

module.exports = require('./webpack.base.babel')({
  // Add hot reloading in development
  entry: {
    myapp: [
      'webpack-hot-middleware/client',
      path.join(process.cwd(), 'src/index.js')
    ]
  },

  // Add development plugins
  plugins: plugins,

  // Tell babel that we want to hot-reload
  babelLoaderOptions: {
    presets: ['react-hmre']
  },

  // Emit a source map for easier debugging
  devtool: 'source-map'
})
